services:
  wordpress:
    image: soulteary/sqlite-wordpress:6.5.3
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./wordpress/html:/var/www/html
      - ./wordpress/php.ini:/usr/local/etc/php/conf.d/custom.ini
